pipelines:
  custom:
    mirror-to-github:
      - step:
          name: Mirror to GitHub
          image: alpine/git
          clone:
            depth: full
          script:
            - git remote add github https://drew-abbo:${GITHUB_MIRROR_TOKEN}@github.com/drew-abbo/bio-visualizer-mirror.git
            - git push --mirror github
